/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Devices": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "LandingSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "LegacyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Notifications": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ScreenshotSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Topic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
  }
}

import "sst"
export {}